In [52]:
#importing the librabries
import numpy as np  #numerical operations in python
import pandas as pd #dataframes-datamnupulations
import matplotlib.pyplot as plt #ploting the graphs

In [53]:
#importing datset

In [54]:
dataset=pd.read_csv('Data.csv')

In [55]:
X=dataset.iloc[:,:-1].values  #all the rows other than last colums
X #x is the instace of hypotesi

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [56]:
y=dataset.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [57]:
#handling missing data

In [58]:
#sklearn #contains large num of libraries of ML
#preprocessing #library contains methods,classes for preprocessing data
#Imputer #is a 'class' that takes care of missing valuesin dataset 

In [59]:
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN',strategy='mean',axis=0) #mean-default value
imputer=imputer.fit(X[:,1:3])  #fit all rows in 1 and 2 column
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [60]:
X[:,1:3]=imputer.transform(X[:,1:3])   #transforms (replaces) the missing value by mean
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [61]:
#categorical data
#-> column with NO numerical data

In [62]:
# encoding categorical data

#LabelEncoder- is a class which handles encoding - categorical values will be encoded

from sklearn.preprocessing import LabelEncoder,OneHotEncoder #LabelEncoder France=1,Spain=2,germany=3
#OneHotEncoder- labels-> 1 0 0 or 0 1 0  --dummy coding 

labelencoder_X=LabelEncoder() #object_name=classname
X[:,0]=labelencoder_X.fit_transform(X[:,0]) #fit and transform 0th column and save it in X itself

onehotencoder=OneHotEncoder(categorical_features=[0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [63]:
#encoding independent values
X=onehotencoder.fit_transform(X).toarray()
print(X)
#dependent values
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [64]:
#Splitting the data

In [65]:
#split dataset into Training and test data set
#sklearn - has large number of ML library
from sklearn.cross_validation import train_test_split #train_test_split is a function/method
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0) 
# test_size=0.2 is 20% as test data 
#AND random_state=0 ->picks any 2 rows as test and to make sure same rows selected in next test  
print(X_train.astype(int))
print('\n')
print(X_test)
X_test.astype(int)


[[    0     1     0    40 63777]
 [    1     0     0    37 67000]
 [    0     0     1    27 48000]
 [    0     0     1    38 52000]
 [    1     0     0    48 79000]
 [    0     0     1    38 61000]
 [    1     0     0    44 72000]
 [    1     0     0    35 58000]]


[[0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]]


array([[    0,     1,     0,    30, 54000],
       [    0,     1,     0,    50, 83000]])

In [66]:
#feature Scaling

In [71]:
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)  #test data need not to learn so no fit on test_data-
#test data is not to learning just to tranform
print(X_train)
print('\n', X_test)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]

 [[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]


In [82]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [83]:
X=dataset.iloc[:,:3]
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [85]:
X=dataset.iloc[:,:3].values
print(X)
y=dataset.iloc[:,2].values
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[72000. 48000. 54000. 61000.    nan 58000. 52000. 79000. 83000. 67000.]
