# date- 03/08/19

In [45]:
print("hello, world!!")

hello, world!!


In [2]:
print(7/3)

2.3333333333333335


In [4]:
print(int(9/2))

4


In [13]:
x='1'
y='2'
z=x+y
print(z)
z=z+'a'
print(z)

12
12a


In [22]:
myvar="""hello, how are you..
good morning"""
print(myvar)
myvar="""hello, how are you..good morning"""
print(myvar)

hello, how are you..
good morning
hello, how are you..good morning


In [46]:
s="Hello"
y="a"
z=s+y
print(z)
s=s+"Hey"
print(s)
print(s[2:5])
print(s[2:-2])


Helloa
HelloHey
llo
lloH


In [48]:
print('a %s parrot' %'happy')

a happy parrot


In [54]:
'Helloo' in s

False

In [59]:
print('hello {} how are you doing, is {} fine?' .format('jack','siya'))

hello jack how are you doing, is siya fine?


In [43]:
val='123'
print(type(val))
print(val+'a')
intval=int(val)
type(intval)
print(intval+3)
print(float(val)+6)

<class 'str'>
123a
126
129.0


In [68]:
string="hello joy"
intval=int(string)

ValueError: invalid literal for int() with base 10: 'hello joy'

In [72]:
nam=input("who are you?")
print('Welcome,',nam)

who are you?siya
Welcome, siya


In [74]:
def add_num(x,y,z=None):
    if(z==None):
        return x+y
    else:
        return x+y+z
print(add_num(1,2))
print(add_num(1,2,3))

3
6


In [77]:
inp=input('Europe floor?')
usf=int(inp)+1
print(usf)

Europe floor?20
21


In [78]:
def add_num(x,y,z=None,flag=False):
    if(z==None):
        return x+y
    else:
        return x+y+z
print(add_num(1,2,flag=True))
print(add_num(1,2,3))

3
6


In [79]:
x=['a','b','c','d']
type(x)

list

In [81]:
[1,2,3,4]+[5.6]+[5,6]

[1, 2, 3, 4, 5.6, 5, 6]

In [82]:
def add_num(x,y):
    return x+y
a=add_num
print(a(3,4))

7


# date:14/08/19

In [44]:
hour=int(input())
rate=float(input())
pay=hour*rate
print(pay)

23
23
529.0


In [13]:
num=7
if num==7:
    print("num is equal to 7")
if num<4:
    print("num is less than 4")
if num<=9:
    print("num is less than or eqastral 9")
if num>=8:
    print("num is greater than or equal")
if num!=1:
    print("num is not equal to 1")

num is equal to 7
num is greater than 9
num is not equal to 1


In [6]:
x=0
if x<2:
    print('below 2')
elif x>=2:
    print('medium')
else:
    print('something else')


below 2


In [9]:
x=5
if x<2:
    print('below 2')
elif x<20:
    print('below 20')
elif x<10:
    print('below 10')
else:
    print('something else')

below 20


In [17]:
string1='hello'
string2=int(string1)
print('first',string2)

ValueError: invalid literal for int() with base 10: 'hello'

In [18]:
string1='hello'
try:
    string2=int(string1)
except:
    string2=-1
print('first',string2)
str1='123'
try:
    str2=int(str1)
except:
    str2=-1
print('second', str2)

first -1
second 123


In [1]:
str1='bob'
try:
    print('hello') #it prints till here
    str2=int(str1) #and skips this 
    print('there')
except:
    str2=-1
print('done!',str2)

hello
done! -1


In [2]:
str1=input('enter a number: ')
try:
    ival=int(str1)
except:
    ival=-1

if ival>0:
    print('nice work')
else:
    print('not a number')

enter a number: 2
nice work


In [46]:
hour=int(input())
rate=int(input())
if(hour>40):
    pay=hour*rate+rate*1.5
else:
    pay=hour*rate
print(pay)

21
53
1113


In [ ]:
#rewrite your pay computation with time-and-a-half for overtime and create a function computepay 
#whcich takes two parameters(hour and rate)


In [4]:
while True:
    line=input('>')
    if line == 'done':
        break
    print(line)
print('done!')

>hello
hello
>done
done!


In [5]:
while True:
    line=input('> ')
    if line[0]=='#':
        continue
    if line=='done':
        break
    print(line)
print('done!')

> hello
hello
> done
done!


In [6]:
for i in [1,2,3,4,5]:
    print(i)
print('Done, printing..!')

1
2
3
4
5
Done, printing..!


In [7]:
f=['joy','siya','jack']
for ele in f:
    print('happy new year', ele)
print('done!, wishing!')

happy new year joy
happy new year siya
happy new year jack
done!, wishing!


In [8]:
print('before')
for things in [9,10,45,26,31]:
    print(things)
print('after')

before
9
10
45
26
31
after


In [47]:
#larest elements in the array
largest_so_far=-1
print('before',largest_so_far)
for num in [10,20,12,32,45,21]:
    if num>largest_so_far:
        largest_so_far=num
    print(largest_so_far,num)
print('after:', largest_so_far)

before -1
10 10
20 20
20 12
32 32
45 45
45 21
after: 45


In [10]:
#searh using a boolean variable
found= False
print('before', found)
for value in [9,10,45,2,3,5,63]:
    if value==3:
        found=True
    print(found,value)
print('after',found)

before False
False 9
False 10
False 45
False 2
True 3
True 5
True 63
after True


In [13]:
#'is' and 'is not' opearator
smallest=None
print('before')
for value in [3,45,12,8,6,52]:
    if smallest is None:
        smallest= value
    elif value<smallest:
        smallest=value
    print(smallest,value)
print('after all iterartion, smallest:',smallest)

before
3 3
3 45
3 12
3 8
3 6
3 52
after all iterartion, smallest: 3


In [14]:
fn='tom mitchell machine learning' .split(' ')[1]
print(fn)

mitchell


In [15]:
chris+2

NameError: name 'chris' is not defined

In [22]:
sales_record={'price':3.45,'num_items':4,'name':'prajna'}
sales_statement= '{} bought {} items at a price of INR {} each for a total of INR{}'
print(sales_statement.format(sales_record['name'],sales_record['num_items'],sales_record['price'],sales_record['num_items']*sales_record['price']))

prajna bought 4 items at a price of INR 3.45 each for a total of INR13.8


In [23]:
time

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 5.01 µs


In [27]:
import time as tm
tm.time()

1565776564.7399895

In [36]:

from datetime import date
#from datetime as time
import datetime as dt
today=date.today()
print('today date is',today)

today date is 2019-08-14


In [40]:
dtnow=dt.datetime.fromtimestamp(tm.time())
print(dtnow)

2019-08-14 15:32:35.943822


In [41]:

today=dt.date.today

In [43]:
class Person:
    institute='Manipal school of information science'
    def set_name(self,new_name):
        self.name=new_name
    def set_location(self,new_loc):
        self.loc=new_loc
    def set_institurte(self,new_inst):
        self.inst=new_inst

person=Person()
person.set_name('prajna')
person.set_location('manipal,udupi,karnataka')
print('{} works in{} and works at {}'.format(person.name,person.loc))

NameError: name 'self_location' is not defined

In [54]:
#map the min function betwen two list
s1=[10.0,20.3,12.36,32.02,10.2]
s2=[2.13,45.3,6.3,1.2,10.1]
small=map(min,s1,s2)  # map function compares the elements parallel in list and returns a value
print(list(small))

[2.13, 20.3, 6.3, 1.2, 10.1]


In [52]:
for i in small:
    print(i)
    

2.13
20.3
6.3
1.2
10.1


In [56]:
#lambda  and listcomprehension
my_func=lambda a,b,c:a+b+c
my_func(2,3,6)

11

In [61]:
people=['Dr. Hello','Mr. joy','Dr. john hhh']
def split_title_and_name(person):
    return person.split()[0]+' '+person.split()[-1]

In [63]:
for person in people:
    print(split_title_and_name(person)==(lambda x:x.split()[0]+' '+x.split()[-1])(person))

True
True
True


In [64]:
list(map(split_title_and_name,people))==list(map(lambda person:person.split()[0]+' '+person.split()[-1],people))

True

In [1]:
#date-24/08/19

In [3]:
def calculatesquare(n):
    return n*n
num=(1,2,3,4)
result=map(calculatesquare,num)
list(result)

[1, 4, 9, 16]

In [5]:
num=(1,2,3,4)
result=map(lambda x:x*x,num)
print(result)
list(result)

[1, 4, 9, 16]

In [8]:
num1=[5,6,7]
num2=[2,3,4]
result=map(lambda n1,n2:n1+n2,num1,num2)
print(list(result))

[7, 9, 11]


In [9]:
num1=[5,6,7]
num2=[2,3,4]
result=lambda n1,n2:n1+n2,num1,num2
print(list(result))

[<function <lambda> at 0x7f48ad6dea60>, [5, 6, 7], [2, 3, 4]]


In [22]:
#split function
people=['Dr. Hello hello hi','Mr. joy jack','Dr. john canady fin']

In [24]:
def split_title_and_name(people):
    title=people.split()[0]
    fname=people.split()[1]
    lastname=people.split()[-1]
    return '{} {} {}'.format(title,lastname,fname)
list(map(split_title_and_name,people))

['Dr. hi Hello', 'Mr. jack joy', 'Dr. fin john']

In [25]:
#lambda functions:

In [26]:
dx=lambda x,y:(x+y)*2
print(dx(5,2))

14


In [27]:
my_list=[1,5,6,7,4,5,2,9]
new_list=map(lambda x:x*2,my_list)
list(new_list)

[2, 10, 12, 14, 8, 10, 4, 18]

In [28]:
my_fun=lambda x,y:x+y
my_fun(10,5)

15

In [64]:
people=['Dr. Hello hello hi','Mr. joy jack','Dr. john canady fin']
def split_title_and_name(people):
    return people.split()[0]+' '+people.split()[-1]

In [65]:
for people in people:
    print(split_title_and_name(people)==(lambda x:x.split()[0]+' '+x.split()[-1])(people))

True
True
True


In [68]:
for people in people:
    print('function result:',split_title_and_name(people))

IndexError: list index out of range

In [55]:
my_list=[]
for num in range(0,20):
    if (num%2==0):
        my_list.append(num)
print(my_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [56]:
my_list=[num for num in range(0,20) if num%2==0]
my_list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [63]:
def times():
    l=[]
    for i in range(10):
        for j in range(10):
            l.append(i*j)
    return l

times()==[i*j for i in range(10) for j in range(10)]
print(times())

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]


# numpy 

In [70]:
import numpy as np

In [72]:
y=np.array([1,2,3])
y

array([1, 2, 3])

In [74]:
m=np.array([[1,2,3],[2,3,5]])
m

array([[1, 2, 3],
       [2, 3, 5]])

In [75]:
#shape identifies he dimentions of an array
m.shape

(2, 3)

In [76]:
#arange(lower limt,upper limit, difference)
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [79]:
#reshape(rows,cols)
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [94]:
#range 0 to 4 is linspced 10 times
lspace=np.linspace(0,4,9)
lspace

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [86]:
#reshape
lspace.resize(3,3)
lspace

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [88]:
#identity matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [93]:
#eyegan values
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
num=np.matrix([[11,12,13],
             [14,15,16],
             [17,18,19]])
print("Mian diagonal elements:",np.diag(num))
print("diagonal elements above main diagonal:",np.diag(num,1))
print("diagonal elements above second main diagonal:",np.diag(num,2))
print("diagonal elements below main diagonal:",np.diag(num,-1))

Mian diagonal elements: [11 15 19]
diagonal elements above main diagonal: [12 16]
diagonal elements above second main diagonal: [13]
diagonal elements below main diagonal: [14 18]


In [101]:
#array repeats n times
np.array([1,2,3]*2)

array([1, 2, 3, 1, 2, 3])

In [102]:
#elemenst repeates n times
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [104]:
p=np.ones([3,3],int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [105]:
#vertical stack-array vertcal
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [108]:
np.vstack([p,2*p,3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [109]:
#horizontal stack
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [112]:
np.hstack([p,5*p,4*p])

array([[1, 1, 1, 5, 5, 5, 4, 4, 4],
       [1, 1, 1, 5, 5, 5, 4, 4, 4],
       [1, 1, 1, 5, 5, 5, 4, 4, 4]])

In [113]:
#operation on arrays

In [116]:
x=np.array([1,2,3])
y=np.array([2,3,5])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)


[3 5 8]
[-1 -1 -2]
[ 2  6 15]
[0.5        0.66666667 0.6       ]
[  1   8 243]


In [117]:
#dot product 1*2+ 2*3 +3*5
x.dot(y)

23

In [118]:
z=np.array([y,y**2])
z

array([[ 2,  3,  5],
       [ 4,  9, 25]])

In [119]:
print(len(z))

2


In [121]:
z.shape

(2, 3)

In [123]:
#transpose
z.T

array([[ 2,  4],
       [ 3,  9],
       [ 5, 25]])

In [124]:
#datatypes
z.dtype

dtype('int64')

In [125]:
#change the data type of an array elements
z=z.astype('f')
z.dtype

dtype('float32')

In [140]:
a=np.array([1,-4,-2,3,5,9,6])
a.sum()

18

In [141]:
a.max()

9

In [142]:
a.min()

-4

In [143]:
a.mean()

2.5714285714285716

In [144]:
a.std()

4.2378277069118075

In [145]:
#index of the maximum umber in array
a.argmax()

5

In [146]:
#index of smallest elements location
a.argmin()

1

In [147]:
s=np.arange(6)
s

array([0, 1, 2, 3, 4, 5])

In [159]:
s=np.arange(10)**2
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [160]:
s[0]

0

In [161]:
s[4]

16

In [162]:
s[-1]

81

In [163]:
s[1:4]

array([1, 4, 9])

In [164]:
s[0:-2]

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [165]:
s[-3:]

array([49, 64, 81])

In [166]:
s[-5:-2]

array([25, 36, 49])

In [167]:
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
import numpy as np
r=np.arange(100)
r.resize((10,10))
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
np.diag(r)

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [12]:
np.diag(r,-2)

array([20, 31, 42, 53, 64, 75, 86, 97])

In [13]:
np.diag(r,1)

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [14]:
#to acess indivisual matrix elemnt
r[2,2]

22

In [15]:
r[3,5]

35

In [16]:
r[3,3:6]

array([33, 34, 35])

In [17]:
#all row upto 2 excluding 2 and [:-1] is stop before last elements -1
r[:2,:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [18]:
r[-1,::1]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
#startwith last row and slicing difference is two
r[-1,::2]

array([90, 92, 94, 96, 98])

In [20]:
r[-1,::3]

array([90, 93, 96, 99])

In [21]:
r[r>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [22]:
r[r<15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
#3*3 matrix
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [24]:
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
r

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
r_copy=r.copy()
r.copy()

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
#keep a copy of origanl array
r_copy[:]=10
print(r_copy,'\n')
print(r)

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [206]:
#0-9 randum numbers and 4*3
test=np.random.randint(0,10,(4,3))
test

array([[8, 4, 7],
       [3, 7, 6],
       [4, 8, 2],
       [9, 6, 3]])

In [208]:
#iterate by row
for row in test:
    print(row)

[8 4 7]
[3 7 6]
[4 8 2]
[9 6 3]


In [209]:
#iterate row and index
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [8 4 7]
row 1 is [3 7 6]
row 2 is [4 8 2]
row 3 is [9 6 3]


In [211]:
#iterate using index
for i in range(len(test)):
    print(test[i])

[8 4 7]
[3 7 6]
[4 8 2]
[9 6 3]


In [212]:
test2=test**2
test2

array([[64, 16, 49],
       [ 9, 49, 36],
       [16, 64,  4],
       [81, 36,  9]])

In [213]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[8 4 7] + [64 16 49] = [72 20 56]
[3 7 6] + [ 9 49 36] = [12 56 42]
[4 8 2] + [16 64  4] = [20 72  6]
[9 6 3] + [81 36  9] = [90 42 12]


# date 31-Aug-2019 numpy

In [32]:
import numpy as np
old=np.array([[1,1,1],
            [1,1,1]])
print(old)
new=old
new[0,:2]=0 #0th row, 2 columns fill with 0
print(new)

print(old)

[[1 1 1]
 [1 1 1]]
[[0 0 1]
 [1 1 1]]
[[0 0 1]
 [1 1 1]]


In [7]:
old=np.array([[1,1,1],
            [1,1,1],
             [1,1,1]])
new=old
new[1:2,1:2]=0
new

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [38]:
# generate 10*10 matrix and fill odd rows with 0's
mat=np.random.randint(0,100,(10,10))
print(mat)
mat1=mat
#mat1[0,:]=0
mat1[1::2,:]=0
print('\n',mat)
mat1

[[62 46 76 57 43 52 88 44 79 82]
 [32 85 82 53 31 31 73 83  1 60]
 [91 80 30 90 91 45 95  8  9 11]
 [98 24 65 80 79 54 52 51 89  2]
 [48 13 43 40 58 54 52 35  3 28]
 [55 42 10 77 73 57 10 10 46  3]
 [75 47 21 20 66 92 69 42 64 36]
 [31 42 15 18 62 22 44 85 82 46]
 [19 10 47 37  8 62 51 66 15 97]
 [50 82 56 55 81 84 92 30 53  1]]

 [[62 46 76 57 43 52 88 44 79 82]
 [ 0  0  0  0  0  0  0  0  0  0]
 [91 80 30 90 91 45 95  8  9 11]
 [ 0  0  0  0  0  0  0  0  0  0]
 [48 13 43 40 58 54 52 35  3 28]
 [ 0  0  0  0  0  0  0  0  0  0]
 [75 47 21 20 66 92 69 42 64 36]
 [ 0  0  0  0  0  0  0  0  0  0]
 [19 10 47 37  8 62 51 66 15 97]
 [ 0  0  0  0  0  0  0  0  0  0]]


array([[62, 46, 76, 57, 43, 52, 88, 44, 79, 82],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [91, 80, 30, 90, 91, 45, 95,  8,  9, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [48, 13, 43, 40, 58, 54, 52, 35,  3, 28],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [75, 47, 21, 20, 66, 92, 69, 42, 64, 36],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [19, 10, 47, 37,  8, 62, 51, 66, 15, 97],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

# pandas

In [42]:
import pandas as pd

In [41]:
pd.Series?

In [12]:
animals=['tiger','bear','moose']
pd.Series(animals)

0    tiger
1     bear
2    moose
dtype: object

In [13]:
num=[1,2,3]
pd.Series(num)

0    1
1    2
2    3
dtype: int64

In [19]:
animals=['tiger','bear',None]
pd.Series(animals)

0    tiger
1     bear
2     None
dtype: object

In [18]:
num=[1,2,None]
pd.Series(num)

0    1.0
1    2.0
2    NaN
dtype: float64

In [20]:
np.nan==None #None is string

False

In [21]:
np.nan==np.nan #not right method to check, nan is similar to none, but numeric value

False

In [22]:
np.isnan(np.nan)

True

In [23]:
sport={'archery':'bhutan',
      'golf':'scotland',
      'sumo':'japan',
      'taekwondo':'south korea'}
s=pd.Series(sport)
s

archery           bhutan
golf            scotland
sumo               japan
taekwondo    south korea
dtype: object

In [24]:
s.index

Index(['archery', 'golf', 'sumo', 'taekwondo'], dtype='object')

In [27]:
s= pd.Series(['tiger','bear','moose'],index=['india','america','canada'])
s

india      tiger
america     bear
canada     moose
dtype: object

In [ ]:
#queying or searching key

In [29]:
sport={'archery':'bhutan',
      'golf':'scotland',
      'sumo':'japan',
      'taekwondo':'south korea'}
s=pd.Series(sport)
s

archery           bhutan
golf            scotland
sumo               japan
taekwondo    south korea
dtype: object

In [30]:
s.iloc[3]

'south korea'

In [31]:
s.loc['golf']

'scotland'

In [32]:
s[3]

'south korea'

In [33]:
s['golf']

'scotland'

In [41]:
sport={99:'bhutan',
      100:'scotland',
      101:'japan',
      102:'south korea'}
sport

{99: 'bhutan', 100: 'scotland', 101: 'japan', 102: 'south korea'}

In [42]:
pd.Series(sport)

99          bhutan
100       scotland
101          japan
102    south korea
dtype: object

In [48]:
s.iloc[2]

'japan'

In [50]:
s=pd.Series([100.00,120.00,101.00,3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

In [51]:
total=0
for item in s:
    total=total+item
print(total)

324.0


In [52]:
total=np.sum(s)
total

324.0

In [59]:
#time take to execute a code
s=pd.Series(np.random.randint(0,10,7)) #btn 0 to 10 generate 7 num
s

0    4
1    7
2    5
3    5
4    0
5    5
6    7
dtype: int64

In [61]:
s=pd.Series(np.random.randint(0,1000,10000))
s.head()

0    706
1    545
2    863
3     46
4     90
dtype: int64

In [62]:
len(s)

10000

In [66]:
%%timeit -n 100
summary=0
for item in s:
    summary=summary+item

100 loops, best of 3: 1.88 ms per loop


In [67]:
%%timeit -n 100
summary=np.sum(s)

100 loops, best of 3: 61.4 µs per loop


In [68]:
#broadcasting

In [69]:
s.head()

0    706
1    545
2    863
3     46
4     90
dtype: int64

In [70]:
s+=2   #add 2 to each item in s
s.head()

0    708
1    547
2    865
3     48
4     92
dtype: int64

In [73]:
s=pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [75]:
s=pd.Series([1,2,3])
s.loc['animal']='bears'
s

0             1
1             2
2             3
animal    bears
dtype: object

In [80]:
original_sport=pd.Series({'archery':'bhutan',
      'cricket':'india',
      'sumo':'japan',
      'taekwondo':'south korea'})
cricket_loving_countries=pd.Series(['Australia',
                                    'India',
                                    'England',
                                   'Newzeeland'],
                                   index=['cricket',
                                          'cricket',
                                          'cricket',
                                         'cricket'])
all_countries=original_sport.append(cricket_loving_countries)
all_countries

archery           bhutan
cricket            india
sumo               japan
taekwondo    south korea
cricket        Australia
cricket            India
cricket          England
cricket       Newzeeland
dtype: object

In [82]:
all_countries.loc['cricket']

cricket         india
cricket     Australia
cricket         India
cricket       England
cricket    Newzeeland
dtype: object

In [89]:
import pandas as pd
p1=pd.Series({'name':'chris','item purchased':'dog food','cost':22.56})
p2=pd.Series({'name':'keien','item purchased':'cat food','cost':2.56})
p3=pd.Series({'name':'john','item purchased':'bird seed','cost':52.56})
df=pd.DataFrame([p1,p2,p3],index=['store1','store2','store1'])
df.head()

cost item purchased   name
store1  22.56       dog food  chris
store2   2.56       cat food  keien
store1  52.56      bird seed   john

In [90]:
df.loc['store2']

cost                  2.56
item purchased    cat food
name                 keien
Name: store2, dtype: object

In [91]:
type(df)

pandas.core.frame.DataFrame

In [92]:
type(df.loc['store2'])

pandas.core.series.Series

In [93]:
df.loc['store1']

cost item purchased   name
store1  22.56       dog food  chris
store1  52.56      bird seed   john

In [98]:
df.loc['store1','cost']

store1    22.56
store1    52.56
Name: cost, dtype: float64

In [99]:
df.T

store1    store2     store1
cost               22.56      2.56      52.56
item purchased  dog food  cat food  bird seed
name               chris     keien       john

In [105]:
df.T

store1    store2     store1
cost               22.56      2.56      52.56
item purchased  dog food  cat food  bird seed
name               chris     keien       john

In [101]:
df.T.loc['cost']

store1    22.56
store2     2.56
store1    52.56
Name: cost, dtype: object

In [107]:
df.loc['store1']['cost']

store1    22.56
store1    52.56
Name: cost, dtype: float64

In [109]:
df.loc[:,['name','cost']]

name   cost
store1  chris  22.56
store2  keien   2.56
store1   john  52.56

In [115]:
df

cost item purchased   name
store1  22.56       dog food  chris
store2   2.56       cat food  keien
store1  52.56      bird seed   john

In [116]:
copy_df=df.copy() #copy the df to other 
copy_df=copy_df.drop('store1')
copy_df

cost item purchased   name
store2  2.56       cat food  keien

In [117]:
copy_df.drop?

In [118]:
del copy_df['name']
copy_df

cost item purchased
store2  2.56       cat food

In [119]:
df

cost item purchased   name
store1  22.56       dog food  chris
store2   2.56       cat food  keien
store1  52.56      bird seed   john

In [120]:
df['location']=None
df

cost item purchased   name location
store1  22.56       dog food  chris     None
store2   2.56       cat food  keien     None
store1  52.56      bird seed   john     None

In [121]:
#data frame indexing and loading

In [122]:
costs=df['cost']
costs

store1    22.56
store2     2.56
store1    52.56
Name: cost, dtype: float64

In [123]:
costs+=2
costs

store1    24.56
store2     4.56
store1    54.56
Name: cost, dtype: float64

In [124]:
df

cost item purchased   name location
store1  24.56       dog food  chris     None
store2   4.56       cat food  keien     None
store1  54.56      bird seed   john     None